### ISSUE TITLE
どんなもので作るかを決めたいです。

### ISSUE THREAD

**Issue by PARKUDP** [PARKUDP/news#14]
次のような感じのものを参考したいと思う。
- https://qiita.com/Pu-of-Parari/items/f3733f0ba48e1df50667
- https://zenn.dev/ovrsa/articles/6e66c50f3b3429
- https://qiita.com/Suntory_N_Water/items/03ea848848cdc434181f

つまり、ReactとFlaskで作ってみたい。

**Comment by PARKUDP** [comment]
Docker導入完了。

**Comment by PARKUDP** [comment]
これから、Figmaで構成を考えた上で取り組む予定である。

**Comment by ogiek0628** [comment]
ある程度、外観や機能が実装できたらデータベース作成*連携希望

**Comment by ogiek0628** [comment]
cnnから情報引いてくるファイル試作終了

**Comment by PARKUDP** [comment]
現在、デプロイ先を悩んでいるが、どっちがいいですか？
現在、Renderの場合だと、課金することになると思います。今は、試作品なので、バックエンド別で、フロントエンド別で立ててやった方がいいですかね。

**Comment by ogiek0628** [comment]
> 現在、デプロイ先を悩んでいるが、どっちがいいですか？ 現在、Renderの場合だと、課金することになると思います。今は、試作品なので、バックエンド別で、フロントエンド別で立ててやった方がいいですかね。

>別にする目的があるのでしょうか？

**Comment by PARKUDP** [comment]
コスト面で、一旦立てることになるという話になるかと思います。

**Comment by ogiek0628** [comment]
なるほどです。
では別で立ててみますか！！！

**Comment by ogiek0628** [comment]
今データベースのディレクトリをfront,backなどと同じ場所にdatabaseとして作成したのですが大丈夫でしょうか？
アドバイス求む

**Comment by PARKUDP** [comment]
いいと思います。front,back,databaseな感じで。

**Comment by ogiek0628** [comment]
news
--back
  +--database

にします。
